name: deploy-app-from-template-test

on:
  repository_dispatch:
    types: ["template-init"]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Access Dispatch Data
      run: |
        echo "caller-ref -- ${{ github.event.client_payload.ref }}"
        echo "caller-repo -- ${{ github.event.client_payload.repo }}"

    - name: Make changes to pull request
      run: | 
        cat > apps/test-app-service-template.yaml <<EOF 
        apiVersion: argoproj.io/v1alpha1 
        kind: Application
        metadata:
          name: test-app-service-template
          namespace: argocd
        spec: 
          project: default 
          syncPolicy:
            automated:
              enabled: true
          source: 
            repoURL: https://github.com/fabio-teichmann/ple-1-internal-dev-platform-mini.git
            targetRevision: HEAD 
            path: manifests/sample-app
          destination: 
            server: https://kubernetes.default.svc
            namespace: default
        EOF 

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.PAT }}
        commit-message: Add app from service-template
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: example-svc-tmpl-integration
        delete-branch: true
        title: '[Example] Add app to AOA'
        body: |
          Integrate app from service-template
          - Create `Application` CRD
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          service-template
          automated pr
        assignees: fabio-teichmann
        reviewers: fabio-teichmann
        # team-reviewers: |
        #   developers
        #   qa-team
        draft: false